//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITNews {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class languageEng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal languageEng() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITNews.languageEng", typeof(languageEng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string bAdd {
            get {
                return ResourceManager.GetString("bAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add admin.
        /// </summary>
        internal static string bAddAdmin {
            get {
                return ResourceManager.GetString("bAddAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add article.
        /// </summary>
        internal static string bAddArticle {
            get {
                return ResourceManager.GetString("bAddArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string bChange {
            get {
                return ResourceManager.GetString("bChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string bChangePassword {
            get {
                return ResourceManager.GetString("bChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string bCreate {
            get {
                return ResourceManager.GetString("bCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string bDodaj {
            get {
                return ResourceManager.GetString("bDodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string bLogOut {
            get {
                return ResourceManager.GetString("bLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string bOk {
            get {
                return ResourceManager.GetString("bOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See articles.
        /// </summary>
        internal static string bSeeArticle {
            get {
                return ResourceManager.GetString("bSeeArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string bSignUp {
            get {
                return ResourceManager.GetString("bSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author :.
        /// </summary>
        internal static string lAuthor {
            get {
                return ResourceManager.GetString("lAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language :.
        /// </summary>
        internal static string lLanguage {
            get {
                return ResourceManager.GetString("lLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password :.
        /// </summary>
        internal static string lNewPassword {
            get {
                return ResourceManager.GetString("lNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password :.
        /// </summary>
        internal static string lOldPassword {
            get {
                return ResourceManager.GetString("lOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string lPassword {
            get {
                return ResourceManager.GetString("lPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reenter password :.
        /// </summary>
        internal static string lPasswordAgain {
            get {
                return ResourceManager.GetString("lPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture :.
        /// </summary>
        internal static string lPicture {
            get {
                return ResourceManager.GetString("lPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user :.
        /// </summary>
        internal static string lSelectUser {
            get {
                return ResourceManager.GetString("lSelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have a user account?.
        /// </summary>
        internal static string lSignUp {
            get {
                return ResourceManager.GetString("lSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text :.
        /// </summary>
        internal static string lText {
            get {
                return ResourceManager.GetString("lText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme :.
        /// </summary>
        internal static string lTheme {
            get {
                return ResourceManager.GetString("lTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title :.
        /// </summary>
        internal static string lTitle {
            get {
                return ResourceManager.GetString("lTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username :.
        /// </summary>
        internal static string lUserName {
            get {
                return ResourceManager.GetString("lUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string rbEngleski {
            get {
                return ResourceManager.GetString("rbEngleski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        internal static string rbSrpski {
            get {
                return ResourceManager.GetString("rbSrpski", resourceCulture);
            }
        }
    }
}
